const type = {
    AUTH_EMAIL: 'AUTH_EMAIL',
    AUTH_PASSWORD: 'AUTH_PASSWORD',
    AUTH_AUTHORIZED: 'AUTH_AUTHORIZED',
    AUTH_ERROR: 'AUTH_ERROR',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_SESSION: 'AUTH_SESSION'
}

export default type