const type = {
    FETCH_GENRES: 'FETCH_GENRES',
    FETCH_SINGLE_GENRE: 'FETCH_SINGLE_GENRE',
    LOADED_GENRES: 'LOADED_GENRES',
    CREATE_GENRE: 'CREATE_GENRE',
    EDIT_GENRE: 'EDIT_GENRE',
    DELETE_GENRE: 'DELETE_GENRE',
    GENRE_EDIT_LOADED: 'GENRE_EDIT_LOADED',
    ERROR_GENRE: 'ERROR_GENRE'
}

export default type