const type = {
    GENRES_FETCH: 'GENRES_FETCH',
    GENRES_FETCH_SINGLE: 'GENRES_FETCH_SINGLE',
    GENRES_LOADED: 'GENRES_LOADED',
    GENRES_CREATE: 'GENRES_CREATE',
    GENRES_EDIT: 'GENRES_EDIT',
    GENRES_DELETE: 'GENRES_DELETE',
    GENRES_EDIT_LOADED: 'GENRES_EDIT_LOADED',
    GENRES_SEARCH: 'GENRES_SEARCH',
    GENRES_SEARCH_VALUE: 'GENRES_SEARCH_VALUE',
    GENRES_SEARCH_LOADING: 'GENRES_SEARCH_LOADING',
    GENRES_SEARCH_LOADED: 'GENRES_SEARCH_LOADED',
    GENRES_RESET: 'GENRES_RESET',
    GENRES_ERROR: 'GENRES_ERROR'
}

export default type