const type = {
    FETCH_KEYWORDS: 'FETCH_KEYWORDS',
    FETCH_SINGLE_KEYWORD: 'FETCH_SINGLE_KEYWORD',
    LOADED_KEYWORDS: 'LOADED_KEYWORDS',
    CREATE_KEYWORD: 'CREATE_KEYWORD',
    EDIT_KEYWORD: 'EDIT_KEYWORD',
    DELETE_KEYWORD: 'DELETE_KEYWORD',
    KEYWORD_EDIT_LOADED: 'KEYWORD_EDIT_LOADED',
    SEARCH_KEYWORDS: 'SEARCH_KEYWORDS',
    SEARCH_KEYWORDS_VALUE: 'SEARCH_KEYWORDS_VALUE',
    LOADING_KEYWORDS_SEARCH: 'LOADING_KEYWORDS_SEARCH',
    ERROR_KEYWORD: 'ERROR_KEYWORD'
}

export default type