const type = {
    FETCH_KEYWORDS: 'FETCH_KEYWORDS',
    LOADED_KEYWORDS: 'LOADED_KEYWORDS',
    CREATE_KEYWORD: 'CREATE_KEYWORD',
    EDIT_KEYWORD: 'EDIT_KEYWORD',
    DELETE_KEYWORD: 'DELETE_KEYWORD',
    ERROR_KEYWORD: 'ERROR_KEYWORD'
}

export default type