const type = {
    KEYWORDS_FETCH: 'KEYWORDS_FETCH',
    KEYWORDS_FETCH_SINGLE: 'KEYWORDS_FETCH_SINGLE',
    KEYWORDS_LOADED: 'KEYWORDS_LOADED',
    KEYWORDS_CREATE: 'KEYWORDS_CREATE',
    KEYWORDS_EDIT: 'KEYWORDS_EDIT',
    KEYWORDS_DELETE: 'KEYWORDS_DELETE',
    KEYWORDS_EDIT_LOADED: 'KEYWORDS_EDIT_LOADED',
    KEYWORDS_SEARCH: 'KEYWORDS_SEARCH',
    KEYWORDS_SEARCH_VALUE: 'KEYWORDS_SEARCH_VALUE',
    KEYWORDS_SEARCH_LOADING: 'KEYWORDS_SEARCH_LOADING',
    KEYWORDS_ERROR: 'KEYWORDS_ERROR'
}

export default type