const type = {
    FETCH_RECOMMENDATIONS: 'FETCH_RECOMMENDATIONS',
    FETCH_SINGLE_RECOMMENDATION: 'FETCH_SINGLE_RECOMMENDATION',
    FETCH_RECOMMENDATION_IMAGE: 'FETCH_RECOMMENDATION_IMAGE',
    LOADED_RECOMMENDATIONS: 'LOADED_RECOMMENDATIONS',
    CREATE_RECOMMENDATION: 'CREATE_RECOMMENDATION',
    EDIT_RECOMMENDATION: 'EDIT_RECOMMENDATION',
    EDIT_LOADED: 'EDIT_LOADED',
    DELETE_RECOMMENDATION: 'DELETE_RECOMMENDATION',
    RECOMMENDATION_IMAGES: 'RECOMMENDATION_IMAGES',
    RECOMMENDATION_IMAGES_VALUE: 'RECOMMENDATION_IMAGES_VALUE',
    RECOMMENDATION_EDIT_LOADED: 'RECOMMENDATION_EDIT_LOADED',
    ERROR_RECOMMENDATION: 'ERROR_RECOMMENDATION',
    RESET_RECOMMENDATION: 'RESET_RECOMMENDATION'
}

export default type