const type = {
    RECOMMENDATION_ITEM_LOADED: 'RECOMMENDATION_ITEM_LOADED',
    RECOMMENDATION_ITEM_FETCH: 'RECOMMENDATION_ITEM_FETCH',
    RECOMMENDATION_ITEM_FETCHING: 'RECOMMENDATION_ITEM_FETCHING',
    RECOMMENDATION_ITEM_SINGLE_FETCH: 'RECOMMENDATION_ITEM_SINGLE_FETCH',
    RECOMMENDATION_ITEM_FETCH_TMDB_DATA: 'RECOMMENDATION_ITEM_FETCH_TMDB_DATA',
    RECOMMENDATION_ITEM_FETCH_TMDB_VALUE: 'RECOMMENDATION_ITEM_FETCH_TMDB_VALUE',
    RECOMMENDATION_ITEM_FETCH_TMDB_SET: 'RECOMMENDATION_ITEM_FETCH_TMDB_SET',
    RECOMMENDATION_ITEM_FETCH_TMDB_TRAILER: 'RECOMMENDATION_ITEM_FETCH_TMDB_TRAILER',
    RECOMMENDATION_ITEM_SOURCE_SEARCH: 'RECOMMENDATION_ITEM_SOURCE_SEARCH',
    RECOMMENDATION_ITEM_SOURCE_VALUE: 'RECOMMENDATION_ITEM_SOURCE_VALUE',
    RECOMMENDATION_ITEM_CREATE: 'RECOMMENDATION_ITEM_CREATE',
    RECOMMENDATION_ITEM_EDIT: 'RECOMMENDATION_ITEM_EDIT',
    RECOMMENDATION_ITEM_EDIT_VALUES: 'RECOMMENDATION_ITEM_EDIT_VALUES',
    RECOMMENDATION_ITEM_EDIT_LOADED: 'RECOMMENDATION_ITEM_EDIT_LOADED',
    RECOMMENDATION_ITEM_DELETE: 'RECOMMENDATION_ITEM_DELETE',
    RECOMMENDATION_ITEM_COMMENTARY: 'RECOMMENDATION_ITEM_COMMENTARY',
    RECOMMENDATION_ITEM_RESET: 'RECOMMENDATION_ITEM_RESET',
    RECOMMENDATION_ITEM_ERROR: 'RECOMMENDATION_ITEM_ERROR',
}

export default type