const type = {
    RECOMMENDATIONS_FETCH: 'RECOMMENDATIONS_FETCH',
    RECOMMENDATIONS_FETCH_SINGLE: 'RECOMMENDATIONS_FETCH_SINGLE',
    RECOMMENDATIONS_FETCH_IMAGE: 'RECOMMENDATIONS_FETCH_IMAGE',
    RECOMMENDATIONS_LOADED: 'RECOMMENDATIONS_LOADED',
    RECOMMENDATIONS_CREATE: 'RECOMMENDATIONS_CREATE',
    RECOMMENDATIONS_EDIT: 'RECOMMENDATIONS_EDIT',
    RECOMMENDATIONS_EDIT_LOADED: 'RECOMMENDATIONS_EDIT_LOADED',
    RECOMMENDATIONS_DELETE: 'RECOMMENDATIONS_DELETE',
    RECOMMENDATIONS_IMAGES: 'RECOMMENDATIONS_IMAGES',
    RECOMMENDATIONS_IMAGES_VALUE: 'RECOMMENDATIONS_IMAGES_VALUE',
    RECOMMENDATIONS_SEARCH: 'RECOMMENDATIONS_SEARCH',
    RECOMMENDATIONS_SEARCH_LOADED: 'RECOMMENDATIONS_SEARCH_LOADED',
    RECOMMENDATIONS_ERROR: 'RECOMMENDATIONS_ERROR',
    RECOMMENDATIONS_RESET: 'RECOMMENDATIONS_RESET'
}

export default type