const type = {
    RECOMMENDATION_ITEM_LOADED: 'RECOMMENDATION_ITEM_LOADED',
    RECOMMENDATION_ITEM_FETCH: 'RECOMMENDATION_ITEM_FETCH',
    RECOMMENDATION_ITEM_SINGLE_FETCH: 'RECOMMENDATION_ITEM_SINGLE_FETCH',
    RECOMMENDATION_ITEM_CREATE: 'RECOMMENDATION_ITEM_CREATE',
    RECOMMENDATION_ITEM_EDIT: 'RECOMMENDATION_ITEM_EDIT',
    RECOMMENDATION_ITEM_DELETE: 'RECOMMENDATION_ITEM_DELETE',
    RECOMMENDATION_ITEM_ERROR: 'RECOMMENDATION_ITEM_ERROR',
}

export default type