const type = {
    SOURCES_FETCH: 'SOURCES_FETCH',
    SOURCES_FETCH_SINGLE: 'SOURCES_FETCH_SINGLE',
    SOURCES_LOADED: 'SOURCES_LOADED',
    SOURCES_CREATE: 'SOURCES_CREATE',
    SOURCES_EDIT: 'SOURCES_EDIT',
    SOURCES_EDIT_LOADED: 'SOURCES_EDIT_LOADED',
    SOURCES_DELETE: 'SOURCES_DELETE',
    SOURCES_ERROR: 'SOURCES_ERROR'
}

export default type