const type = {
    FETCH_SOURCES: 'FETCH_SOURCES',
    FETCH_SINGLE_SOURCE: 'FETCH_SINGLE_SOURCE',
    LOADED_SOURCES: 'LOADED_SOURCES',
    CREATE_SOURCE: 'CREATE_SOURCE',
    EDIT_SOURCE: 'EDIT_SOURCE',
    DELETE_SOURCE: 'DELETE_SOURCE',
    SOURCE_EDIT_LOADED: 'SOURCE_EDIT_LOADED',
    ERROR_SOURCE: 'ERROR_SOURCE'
}

export default type