const type = {
    LIST_LOADED: 'LIST_LOADED',
    EDIT_LOADED: 'EDIT_LOADED',
    FETCH_USERS: 'FETCH_USERS',
    CREATE_USER: 'CREATE_USER',
    FETCH_SINGLE_USER: 'FETCH_SINGLE_USER',
    USER_REGISTER: 'USER_REGISTER',
    USER_EDITED: 'USER_EDITED',
    USER_DELETED: 'USER_DELETED',
    USER_ERROR: 'USER_ERROR'
}

export default type