const type = {
    LIST_LOADED: 'LIST_LOADED',
    FETCH_USERS: 'FETCH_USERS',
    CREATE_USER: 'CREATE_USER',
    FETCH_SINGLE_USER: 'FETCH_SINGLE_USER',
    USER_REGISTER: 'USER_REGISTER',
    USER_ERROR: 'USER_ERROR'
}

export default type