const type = {
    USERS_FETCH: 'USERS_FETCH',
    USERS_FETCH_SINGLE: 'USERS_FETCH_SINGLE',
    USERS_LOADED: 'USERS_LOADED',
    USERS_REGISTER: 'USERS_REGISTER',
    USERS_EDIT: 'USERS_EDIT',
    USERS_EDIT_LOADED: 'USERS_EDIT_LOADED',
    USERS_DELETE: 'USERS_DELETE',
    USERS_SEARCH: 'USERS_SEARCH',
    USERS_ERROR: 'USERS_ERROR'
}

export default type